### ISSUE TITLE
Select the h1 element to properly size the text.

### ISSUE THREAD

**Issue by josephtkim** [mjyergin/prj-rev-bwfs-dasmoto#1]
By applying the font-size to the div element, it will also cause the nested elements, including the h1, to become much larger than usual. To fix this, you can just select the h1 directly, and keep the properties for the selector, like so

```css
#header h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  /*background color is for background image fallback since I'm linking to this one.*/
  background-color: rgb(165,206,206);
  color: khaki;
  font-size: 100px;
  font-weight: bold;
  text-align: center;
}
```
