### ISSUE TITLE
Simplify: Apply shared properties to multiple elements at once rather than individually.

### ISSUE THREAD

**Issue by josephtkim** [mjyergin/prj-rev-bwfs-dasmoto#5]
It is always good to try and simplify the CSS code as much as possible to make the code cleaner and more concise. You did a great job applying this to the font-family property, and it would be a good idea to apply this for the font-weight property as well, like

```css
#header, .sections, .price {
  font-weight: bold;
}
```
